import spacy
from spacy.training import Example
import random
import os
import pdfplumber
import re


def extract_text_from_pdf(file_path):
    text = ""
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text
    return text


def clean_text(text):
    text = text.lower()
    text = re.sub(r"\W+", " ", text)
    text = re.sub(r"\d+", "", text)
    return text


def extract_skills_section(text):

    section_headers = ["skills", "technical skills", "core competencies"]

    for header in section_headers:
        skills_start = re.search(r"\b" + re.escape(header) + r"\b", text.lower())
        if skills_start:

            skills_section = text[skills_start.start() :]

            next_heading = re.search(r"\n\s*\w+\s*:", skills_section)
            if next_heading:
                skills_section = skills_section[: next_heading.start()]
            return skills_section.strip()

    return text.strip()


skill_keywords = [
    "python",
    "java",
    "c++",
    "c#",
    "javascript",
    "html",
    "css",
    "php",
    "sql",
    "mongodb",
    "django",
    "flask",
    "react",
    "angular",
    "vue.js",
    "node.js",
    "express.js",
    "tensorflow",
    "keras",
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "docker",
    "kubernetes",
    "git",
    "svn",
    "bash",
    "linux",
    "aws",
    "azure",
    "gcp",
    "firebase",
    "rabbitmq",
    "graphql",
    "web scraping",
    "beautifulsoup",
    "selenium",
    "tweepy",
    "opencv",
    "natural language processing",
    "nlp",
    "computer vision",
    "image processing",
    "deep learning",
    "machine learning",
    "reinforcement learning",
    "devops",
    "terraform",
    "ansible",
    "jenkins",
    "travis-ci",
    "splunk",
    "elastic search",
    "hadoop",
    "spark",
    "hive",
    "pig",
    "hdfs",
    "kafka",
    "power bi",
    "tableau",
    "qlikview",
    "ssis",
    "ssrs",
    "ssas",
    "data warehousing",
    "data engineering",
    "data science",
    "data analytics",
    "big data",
    "etl",
    "data pipelines",
    "microservices",
    "restful apis",
    "soap",
    "mvc",
    "oop",
    "tdd",
    "bdd",
    "integration testing",
    "unit testing",
    "ci/cd pipelines",
    "load balancing",
    "proxy servers",
    "reverse proxies",
    "dns",
    "network security",
    "firewalls",
    "penetration testing",
    "ethical hacking",
    "cybersecurity",
    "ssl/tls",
    "encryption",
    "hashing",
    "cryptography",
    "saml",
    "oauth",
    "jwt",
    "xml",
    "json",
    "yaml",
    "protobuf",
    "socket programming",
    "embedded systems",
    "firmware development",
    "assembly language",
    "verilog",
    "vhdl",
    "arduino",
    "raspberry pi",
    "fpga",
    "circuit design",
    "next.js",
    "prisma",
    "financial modeling",
    "budgeting",
    "forecasting",
    "variance analysis",
    "accounting",
    "bookkeeping",
    "taxation",
    "auditing",
    "ifrs",
    "gaap",
    "financial reporting",
    "cost accounting",
    "capital budgeting",
    "investment analysis",
    "portfolio management",
    "stock trading",
    "options trading",
    "derivatives",
    "hedging",
    "risk management",
    "credit risk",
    "market risk",
    "liquidity risk",
    "fraud detection",
    "financial analysis",
    "financial statement analysis",
    "mergers and acquisitions",
    "due diligence",
    "valuation",
    "corporate finance",
    "treasury management",
    "internal controls",
    "sox compliance",
    "esg reporting",
    "sap fico",
    "oracle financials",
    "quickbooks",
    "xero",
    "netsuite",
    "peachtree",
    "microsoft dynamics",
    "sage",
    "excel",
    "pivot tables",
    "vlookup",
    "macros",
    "power query",
    "sql for finance",
    "financial databases",
    "bloomberg terminal",
    "reuters eikon",
    "s&p capital iq",
    "patient care",
    "diagnosis",
    "treatment planning",
    "surgical procedures",
    "medical imaging",
    "radiology",
    "phlebotomy",
    "clinical research",
    "medical research",
    "epidemiology",
    "public health",
    "pharmaceuticals",
    "drug development",
    "biostatistics",
    "genetics",
    "bioinformatics",
    "medical coding",
    "icd-10",
    "cpt coding",
    "medical billing",
    "healthcare administration",
    "ehr systems",
    "epic systems",
    "cerner",
    "meditech",
    "allscripts",
    "pacs",
    "dental procedures",
    "pediatrics",
    "oncology",
    "cardiology",
    "neurology",
    "psychiatry",
    "orthopedics",
    "anesthesia",
    "critical care",
    "emergency medicine",
    "nursing",
    "registered nurse",
    "certified nursing assistant",
    "clinical trials",
    "fda regulations",
    "medical device regulations",
    "hipaa compliance",
    "infection control",
    "pharmacology",
    "vaccinology",
    "digital marketing",
    "seo",
    "sem",
    "content marketing",
    "social media marketing",
    "email marketing",
    "affiliate marketing",
    "influencer marketing",
    "google analytics",
    "facebook ads",
    "google ads",
    "instagram marketing",
    "linkedin marketing",
    "pinterest marketing",
    "youtube marketing",
    "tiktok marketing",
    "content creation",
    "copywriting",
    "blogging",
    "wordpress",
    "wix",
    "squarespace",
    "ad copywriting",
    "conversion rate optimization",
    "a/b testing",
    "heatmaps",
    "crm systems",
    "hubspot",
    "salesforce",
    "zoho crm",
    "lead generation",
    "sales forecasting",
    "cold calling",
    "sales presentations",
    "closing sales",
    "account management",
    "key account management",
    "business development",
    "market research",
    "competitive analysis",
    "brand management",
    "product marketing",
    "pricing strategy",
    "public relations",
    "media relations",
    "advertising",
    "media buying",
    "trade shows",
    "event marketing",
    "direct mail marketing",
    "mechanical engineering",
    "electrical engineering",
    "civil engineering",
    "chemical engineering",
    "aerospace engineering",
    "automotive engineering",
    "industrial engineering",
    "manufacturing processes",
    "lean manufacturing",
    "six sigma",
    "process optimization",
    "quality control",
    "product design",
    "cad",
    "autocad",
    "solidworks",
    "catia",
    "ansys",
    "finite element analysis",
    "fmea",
    "dfmea",
    "root cause analysis",
    "statistical process control",
    "supply chain management",
    "inventory management",
    "logistics",
    "warehouse management",
    "procurement",
    "vendor management",
    "plc programming",
    "robotics",
    "automation",
    "electrical circuits",
    "microcontrollers",
    "pneumatics",
    "hydraulics",
    "control systems",
    "hvac systems",
    "thermodynamics",
    "fluid dynamics",
    "power generation",
    "renewable energy",
    "wind energy",
    "solar energy",
    "energy management",
    "environmental engineering",
    "structural engineering",
    "graphic design",
    "ui/ux design",
    "web design",
    "adobe photoshop",
    "adobe illustrator",
    "adobe xd",
    "figma",
    "sketch",
    "invision",
    "wireframing",
    "prototyping",
    "user research",
    "user personas",
    "user testing",
    "interaction design",
    "visual design",
    "typography",
    "color theory",
    "motion graphics",
    "video editing",
    "adobe premiere pro",
    "final cut pro",
    "after effects",
    "3d modeling",
    "blender",
    "maya",
    "cinema 4d",
    "3ds max",
    "product design",
    "industrial design",
    "animation",
    "storyboarding",
    "character design",
    "concept art",
    "photography",
    "videography",
    "audio editing",
    "sound design",
    "recruitment",
    "talent acquisition",
    "headhunting",
    "interviewing",
    "onboarding",
    "employee engagement",
    "hr policies",
    "compliance",
    "payroll",
    "benefits administration",
    "employee relations",
    "performance management",
    "succession planning",
    "workforce planning",
    "learning and development",
    "training and development",
    "leadership development",
    "organizational development",
    "change management",
    "employee retention",
    "compensation and benefits",
    "labor laws",
    "conflict resolution",
    "mediation",
    "diversity and inclusion",
    "workplace safety",
    "hr analytics",
    "human capital management",
    "sap hcm",
    "workday",
    "people management",
    "team building",
    "strategic planning",
    "decision making",
    "negotiation",
    "project management",
    "agile",
    "scrum",
    "kanban",
    "lean",
    "waterfall",
    "pmp",
    "prince2",
    "stakeholder management",
    "contract law",
    "intellectual property law",
    "corporate law",
    "mergers and acquisitions",
    "legal research",
    "legal writing",
    "litigation",
    "dispute resolution",
    "arbitration",
    "mediation",
    "regulatory compliance",
    "anti-money laundering",
    "data privacy",
    "gdpr",
    "hipaa",
    "patent law",
    "trademark law",
    "employment law",
    "labor law",
    "commercial law",
    "tax law",
    "real estate law",
    "environmental law",
    "corporate governance",
    "risk management",
    "internal auditing",
    "fraud prevention",
    "ethics and compliance",
    "policy development",
    "curriculum development",
    "lesson planning",
    "instructional design",
    "e-learning",
    "online teaching",
    "classroom management",
    "student engagement",
    "special education",
    "early childhood education",
    "adult learning",
    "edtech",
    "educational psychology",
    "blended learning",
    "flipped classroom",
    "learning management systems",
    "moodle",
    "blackboard",
    "canvas",
    "google classroom",
    "assessment design",
    "formative assessment",
    "summative assessment",
    "feedback and evaluation",
    "teacher training",
    "teacher leadership",
    "curriculum alignment",
    "education policy",
    "education technology",
    "academic advising",
    "research",
    "data collection",
    "data analysis",
    "report writing",
    "presentation skills",
    "public speaking",
    "time management",
    "problem-solving",
    "critical thinking",
    "creativity",
    "innovation",
    "emotional intelligence",
    "leadership",
    "teamwork",
    "collaboration",
    "adaptability",
    "conflict resolution",
    "customer service",
    "relationship management",
    "event planning",
    "budget management",
    "python",
    "sql",
    "data analysis",
    "excel",
    "power bi",
    "tableau",
    "data visualization",
    "statistics",
    "machine learning",
    "data cleaning",
    "data modeling",
    "data mining",
    "business intelligence",
    "dashboarding",
    "data warehousing",
    "report writing",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "big data",
    "etl processes",
    "a/b testing",
    "html",
    "css",
    "javascript",
    "react",
    "angular",
    "vue.js",
    "node.js",
    "express.js",
    "django",
    "flask",
    "bootstrap",
    "php",
    "ruby on rails",
    "typescript",
    "graphql",
    "restful apis",
    "nosql",
    "mongodb",
    "firebase",
    "version control",
    "git",
    "responsive design",
    "sass",
    "webpack",
    "tailwind css",
    "npm",
    "json",
    "java",
    "kotlin",
    "android sdk",
    "android studio",
    "xml",
    "android jetpack",
    "retrofit",
    "glide",
    "room database",
    "mvvm",
    "mvc",
    "sqlite",
    "gradle",
    "push notifications",
    "material design",
    "ui/ux design",
    "google play services",
    "threading",
    "background services",
    "dagger",
    "coroutines",
    "dagger hilt",
    "deep learning",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "nlp",
    "opencv",
    "computer vision",
    "neural networks",
    "data augmentation",
    "natural language processing",
    "reinforcement learning",
    "keras",
    "jupyter notebooks",
    "gans",
    "transfer learning",
    "hyperparameter tuning",
    "docker",
    "kubernetes",
    "devops",
    "linux",
    "bash",
    "ci/cd pipelines",
    "microservices",
    "nginx",
    "cloud deployment",
    "bash scripting",
    "jenkins",
    "terraform",
    "ansible",
    "cloud infrastructure",
    "vagrant",
    "shell scripting",
    "configuration management",
    "cloud computing",
    "cloud architecture",
    "serverless computing",
    "vmware",
    "cloud migration",
    "storage management",
    "scaling",
    "backup and recovery",
    "c",
    "c++",
    "embedded systems",
    "microcontrollers",
    "arduino",
    "raspberry pi",
    "fpga",
    "verilog",
    "vhdl",
    "real-time operating systems",
    "rtems",
    "sensor interfacing",
    "uart",
    "spi",
    "i2c",
    "pcb design",
    "circuit design",
    "analog electronics",
    "signal processing",
    "embedded linux",
    "power management",
    "firmware development",
    "financial statements",
    "accounts payable",
    "accounts receivable",
    "bookkeeping",
    "payroll",
    "tax preparation",
    "audit",
    "cost analysis",
    "balance sheets",
    "income statements",
    "gaap",
    "budgeting",
    "bank reconciliations",
    "quickbooks",
    "tally",
    "financial reporting",
    "variance analysis",
    "cash flow management",
    "financial forecasting",
    "inventory management",
    "legal research",
    "court procedures",
    "contract law",
    "criminal law",
    "civil litigation",
    "intellectual property",
    "legal writing",
    "case management",
    "client relations",
    "legal counseling",
    "dispute resolution",
    "mediation",
    "negotiation",
    "court documentation",
    "corporate law",
    "crop management",
    "soil science",
    "pest control",
    "organic farming",
    "irrigation systems",
    "agricultural machinery",
    "crop rotation",
    "precision farming",
    "agronomy",
    "plant genetics",
    "soil fertility",
    "farm management",
    "sustainable agriculture",
    "greenhouse management",
    "climate impact",
    "water conservation",
    "fertilizer application",
    "plant pathology",
    "fashion design",
    "sketching",
    "pattern making",
    "textile selection",
    "garment construction",
    "apparel design software",
    "illustration",
    "trend analysis",
    "color theory",
    "fashion styling",
    "sewing",
    "clothing materials",
    "fashion marketing",
    "fashion photography",
    "retail",
    "visual merchandising",
    "fashion production",
    "fabric technology",
    "fashion history",
    "drawing",
    "painting",
    "sculpting",
    "graphic design",
    "digital art",
    "3D modeling",
    "photoshop",
    "illustrator",
    "creative vision",
    "artistic styles",
    "storyboarding",
    "animation",
    "gallery curation",
    "printmaking",
    "character design",
    "automobile diagnostics",
    "engine repair",
    "brake systems",
    "electrical systems",
    "transmission repair",
    "vehicle maintenance",
    "suspension systems",
    "engine tuning",
    "automotive electronics",
    "mechanical systems",
    "fuel injection",
    "vehicle safety",
    "hvac systems",
    "diagnostic tools",
    "air conditioning",
    "wheel alignment",
    "hydraulics",
    "automobile assembly",
    "chassis repair",
    "vehicle inspection",
    "automotive air conditioning",
    "manual transmission",
    "automatic transmission",
    "diesel engines",
    "lubrication systems",
    "aerodynamics",
    "aircraft design",
    "engine systems",
    "flight control systems",
    "avionics",
    "fluid mechanics",
    "thermodynamics",
    "flight testing",
    "navigation systems",
    "aircraft manufacturing",
    "cfd simulation",
    "maintenance procedures",
    "aircraft structure",
    "propulsion systems",
    "aerospace materials",
    "flight performance",
    "noise control",
    "rotorcraft design",
    "satellite systems",
    "flight dynamics",
    "financial analysis",
    "investment banking",
    "risk assessment",
    "loan processing",
    "credit analysis",
    "financial modeling",
    "regulatory compliance",
    "anti-money laundering",
    "account management",
    "investment strategies",
    "corporate banking",
    "wealth management",
    "customer service",
    "portfolio management",
    "cash flow analysis",
    "financial forecasting",
    "customer support",
    "call center operations",
    "client communication",
    "issue resolution",
    "crm tools",
    "email support",
    "salesforce",
    "zendesk",
    "multitasking",
    "team collaboration",
    "voice support",
    "non-voice support",
    "quality assurance",
    "inbound calls",
    "outbound calls",
    "technical support",
    "upselling",
    "cross-selling",
    "data entry",
    "customer satisfaction",
    "ticketing systems",
    "workforce management",
    "performance tracking",
    "telemarketing",
]  # Extracting the valid skills from the provided JSON data and putting them into an array.




def find_skills_in_text(text):
    entities = []
    for skill in skill_keywords:

        for match in re.finditer(r"\b" + re.escape(skill) + r"\b", text):
            start, end = match.start(), match.end()

            overlap = False
            for existing_start, existing_end, _ in entities:
                if not (end <= existing_start or start >= existing_end):
                    overlap = True
                    break
            if not overlap:
                entities.append((start, end, "SKILL"))

    entities.sort(key=lambda x: x[0])
    return {"entities": entities}


def load_training_data(folder_path):
    training_data = []
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith(".pdf"):
                file_path = os.path.join(root, file)
                print(f"Processing file: {file_path}")
                text = extract_text_from_pdf(file_path)
                skills_section = extract_skills_section(text)
                cleaned_text = clean_text(skills_section)

                annotations = find_skills_in_text(cleaned_text)

                if annotations["entities"]:
                    # print(f"Extracted Text: {cleaned_text}")
                    # print(f"Annotations: {annotations}")
                    training_data.append((cleaned_text, annotations))
    return training_data


nlp = spacy.load("en_core_web_sm")


ner = nlp.get_pipe("ner")
ner.add_label("SKILL")


TRAIN_DATA = load_training_data("data/data/")


pipe_exceptions = ["ner"]
unaffected_pipes = [pipe for pipe in nlp.pipe_names if pipe not in pipe_exceptions]


with nlp.disable_pipes(*unaffected_pipes):
    nlp.initialize()

    for epoch in range(3):
        random.shuffle(TRAIN_DATA)
        losses = {}
        for text, annotations in TRAIN_DATA:
            doc = nlp.make_doc(text)
            example = Example.from_dict(doc, annotations)
            nlp.update([example], drop=0.5, losses=losses)
        print(f"Epoch {epoch}, Losses: {losses}")


nlp.to_disk("skill_ner_model2")
